QuanLyNhanSu/Areas/admin/Controllers/QuanLyLuongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Data;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class QuanLyLuongController : AuthorController
    //     public class QuanLyLuongController : AuthorController
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/QuanLyLuong/
        public ActionResult Index()
        {
            var list = db.Luongs.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult SuaBangLuong(String id)
        {
            var luong = db.Luongs.Where(n => n.MaNhanVien == id).SingleOrDefault();
            return View(luong);
        }
        [HttpPost]
        public ActionResult SuaBangLuong(Luong luong, CapNhatLuong up)
        {
            var l = db.Luongs.Where(n => n.MaNhanVien == luong.MaNhanVien).FirstOrDefault();
            if (l != null)
            {
                //  l.MaNhanVien = luong.MaNhanVien;
                if (int.Parse(up.LuongSauCapNhat.ToString()) != 0)
                {
                    l.LuongToiThieu = up.LuongSauCapNhat;
                }

                l.BHXH = luong.BHXH == null ? 0 : luong.BHXH;
                l.BHYT = luong.BHYT == null ? 0 : luong.BHYT;
                l.BHTN = luong.BHTN == null ? 0 : luong.BHTN;
             //   l.PhuCap = luong.PhuCap;
                l.ThueThuNhap = luong.ThueThuNhap;
                l.HeSoLuong = luong.HeSoLuong;

                //tao table luu lai moi lan cap nhat luong
                CapNhatLuong capNhat = new CapNhatLuong();
                capNhat.NgayCapNhat = DateTime.Now.Date;
                capNhat.MaNhanVien = luong.MaNhanVien;
                capNhat.LuongHienTai = luong.LuongToiThieu;
                capNhat.LuongSauCapNhat = up.LuongSauCapNhat;
                capNhat.BHXH = luong.BHXH;
                capNhat.BHYT = luong.BHYT;
                capNhat.BHTN = luong.BHTN;
              //  capNhat.PhuCap = luong.PhuCap;
                capNhat.ThueThuNhap = luong.ThueThuNhap;
                capNhat.HeSoLuong = luong.HeSoLuong;

                db.CapNhatLuongs.Add(capNhat);
                db.SaveChanges();
            }

            return Redirect("/admin/QuanLyLuong");
        }
        //end update lương

        public ActionResult ThanhToanLuong()
        {
            var luong = db.Luongs.ToList();

            DateTime now = DateTime.Now;
            foreach (var item in luong)
            {
                ChiTietLuong ct = new ChiTietLuong();
                ct.MaChiTietBangLuong = "t" + now.Month.ToString();
                ct.MaNhanVien = item.MaNhanVien;
                var ctl = db.ChiTietLuongs.Where(n => n.MaNhanVien == ct.MaNhanVien).FirstOrDefault();
                //ct.MaChiTietBangLuong = t+dem.ToString();

                double tienthue = 0, phucap = 0;
                double tong = 0;
                item.HeSoLuong = item.HeSoLuong == null ? 0 : item.HeSoLuong;
                ct.LuongCoBan = item.LuongToiThieu * (double)item.HeSoLuong;

                item.BHXH = item.BHXH == null ? 0 : item.BHXH;
                ct.BHXH = item.BHXH * item.LuongToiThieu / 100;

                item.BHYT = item.BHYT == null ? 0 : item.BHYT;
                ct.BHYT = item.BHYT * item.LuongToiThieu / 100;

                item.BHTN = item.BHTN == null ? 0 : item.BHTN;
                ct.BHTN = item.BHTN * item.LuongToiThieu / 100;


                item.PhuCap = item.PhuCap == null ? 0 : item.PhuCap;
                phucap = item.LuongToiThieu * (double)item.PhuCap;
                ct.PhuCap = phucap;


                item.ThueThuNhap = item.ThueThuNhap == null ? 0 : item.ThueThuNhap;
                tienthue = item.LuongToiThieu * (int)item.ThueThuNhap / 100;
                ct.ThueThuNhap = tienthue;

                ct.NgayNhanLuong = DateTime.Now.Date;
                ct.TienThuong = 0;
                ct.TienPhat = 0;
                tong = tong + ct.LuongCoBan - (double)(ct.BHXH + ct.BHYT + ct.BHTN) - (double)ct.ThueThuNhap + (double)ct.PhuCap;
                ct.TongTienLuong = tong.ToString();
                if (ctl == null)
                {
                    db.ChiTietLuongs.Add(ct);
                }
                ViewBag.ok = "thanh toán thành công";
                db.SaveChanges();
            }
            return Redirect("/admin/QuanLyLuong");
        }


        public ActionResult ThanhToanMotNhanVien(String id)
        {
            var nv = db.NhanViens.Where(n => n.MaNhanVien == id).FirstOrDefault();
            if (nv != null)
            {
                //tim xem da co trong chi tiet lương chưa
                var ctl = db.ChiTietLuongs.Where(n => n.MaNhanVien == id).FirstOrDefault();
                //tìm bảng lương tương ứng với nhân viên
                var luongthang = db.Luongs.Where(n => n.MaNhanVien == id).FirstOrDefault();
                ChiTietLuong ct = new ChiTietLuong();
                DateTime now = DateTime.Now;
                double tienthue = 0, tong = 0, phucap = 0;

                ct.MaChiTietBangLuong = "t" + now.Month.ToString();
                ct.MaNhanVien = luongthang.MaNhanVien;

                ct.LuongCoBan = luongthang.LuongToiThieu * (double)luongthang.HeSoLuong;

                luongthang.BHXH = luongthang.BHXH == null ? 0 : luongthang.BHXH;
                ct.BHXH = luongthang.BHXH * luongthang.LuongToiThieu / 100;

                luongthang.BHYT = luongthang.BHYT == null ? 0 : luongthang.BHYT;
                ct.BHYT = luongthang.BHYT * luongthang.LuongToiThieu / 100;

                luongthang.BHTN = luongthang.BHTN == null ? 0 : luongthang.BHTN;
                ct.BHTN = luongthang.BHTN * luongthang.LuongToiThieu / 100;

                luongthang.PhuCap = luongthang.PhuCap == null ? 0 : luongthang.PhuCap;
                phucap = luongthang.LuongToiThieu * (double)luongthang.PhuCap;
                ct.PhuCap = phucap;


                luongthang.ThueThuNhap = luongthang.ThueThuNhap == null ? 0 : luongthang.ThueThuNhap;
                tienthue = (double)luongthang.LuongToiThieu * (double)luongthang.ThueThuNhap / 100;
                ct.ThueThuNhap = (double)tienthue;
                ct.NgayNhanLuong = DateTime.Now.Date;
                ct.TienThuong = 0;
                ct.TienPhat = 0;
                tong = tong + ct.LuongCoBan - (double)(ct.BHXH + ct.BHYT + ct.BHTN) - (double)ct.ThueThuNhap + (double)ct.PhuCap;
                ct.TongTienLuong = tong.ToString();
                if (ctl == null)
                {
                    ViewBag.ok = "thanh toán thành công";
                    db.ChiTietLuongs.Add(ct);
                }
                db.SaveChanges();

            }
            return Redirect("/admin/QuanLyLuong");
        }

        public ActionResult DanhSachNhanLuong()
        {
            var list = db.ChiTietLuongs.ToList();
            return View(list);
        }
        public ActionResult XuatFileLuong(String id)
        {
            //var l = db.ChiTietLuongs.Where(n => n.MaChiTietBangLuong == id).ToList();
            var ds = db.ChiTietLuongs.ToList();
            //===================================================
            DataTable dt = new DataTable();
            //Add Datacolumn
            DataColumn workCol = dt.Columns.Add("Mã nhân viên", typeof(String));
            dt.Columns.Add("Lương cơ bản", typeof(String));
            dt.Columns.Add("BHXH", typeof(String));
            dt.Columns.Add("Phụ cấp", typeof(String));
            dt.Columns.Add("Thuế thu nhập", typeof(String));
            dt.Columns.Add("Ngày nhận lương", typeof(String));
            dt.Columns.Add("Thực lãnh", typeof(String));

            //Add in the datarow


            foreach (var item in ds)
            {
                DataRow newRow = dt.NewRow();
                newRow["Mã nhân viên"] = item.MaNhanVien;
                newRow["Lương cơ bản"] = item.LuongCoBan;
                newRow["BHXH"] = item.BHXH;
                newRow["Phụ cấp"] = item.PhuCap;
                newRow["Thuế thu nhập"] = item.ThueThuNhap;
                newRow["Ngày nhận lương"] = item.NgayNhanLuong;
                newRow["Thực lãnh"] = item.TongTienLuong;


                dt.Rows.Add(newRow);
            }

            //====================================================
            var gv = new GridView();
            //gv.DataSource = ds;
            gv.DataSource = dt;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;

            Response.AddHeader("content-disposition", "attachment; filename=danh-sach-luong.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return Redirect("/admin/QuanLyLuong");
        }


        public ActionResult QuaTrinhTangLuong(String id)
        {
            var tangluong = db.CapNhatLuongs.Where(n => n.MaNhanVien == id).ToList();
            if (tangluong != null)
            {
                return View(tangluong);
            }
            return Redirect("/admin/QuanLyLuong");
        }// EndEv
    }   //end class
}

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/DanhSachNhanLuong.cshtml
@model IEnumerable<QuanLyNhanSu.Models.ChiTietLuong>
@{
    ViewBag.Title = "Danh sách nhận lương";
}


<div class="">
    <div class="">
        <h1 class="page-header">
            Danh sách Lương nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i><a href="@Url.Action("index","QuanLyLuong")"> Lương</a>
            </li>
        </ol>
    </div>
</div>
<div style="margin:10px">

    <div class="form-group">
        <a class="btn btn-primary" href="@Url.Action("XuatFileLuong", "QuanLyLuong", new {@id = "" })"> Xuất file</a>
        @*<select >
            <option value="t1">Tháng 1</option>
            <option value="t1">Tháng 1</option>
            <option value="t2">Tháng 2</option>
            <option value="t3">Tháng 3</option>
            <option value="t4">Tháng 4</option>
            <option value="t5">Tháng 5</option>
            <option value="t6">Tháng 6</option>
            <option value="t7">Tháng 7</option>
            <option value="t8">Tháng 8</option>
            <option value="t9">Tháng 9</option>
            <option value="t10">Tháng 10</option>
            <option value="t11">Tháng 11</option>
            <option value="t12">Tháng 12</option>
        </select>*@
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-striped table-hover table-bordered ">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>

                <th>
                    Lương cơ bản
                </th>
                <th>
                    Bảo hiểm
                </th>
                <th>
                    Phụ cấp
                </th>
                <th>
                    Thuế thu nhập
                </th>
                @*<th>
                        Tiền thưởng
                    </th>
                    <th>
                        Tiền phạt
                    </th>*@
                <th>
                    Ngày nhận lương
                </th>
                <th>
                    Thực lãnh
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaNhanVien)
                </td>

                <td>
                    @string.Format("{0:#,#}", @item.LuongCoBan).Replace(",", ",")

                </td>
                <td>
                    <table class="table table-bordered">
                        <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                        <tr>
                            <td>@string.Format("{0:#,#}", @item.BHXH).Replace(",", ",")</td>
                            <td>@string.Format("{0:#,#}", @item.BHYT).Replace(",", ",")</td>
                            <td>@string.Format("{0:#,#}", @item.BHTN).Replace(",", ",")</td>
                        </tr>
                    </table>
                </td>
                <td>
                    @string.Format("{0:#,#}", @item.PhuCap).Replace(",", ",")

                </td>
                <td>
                    @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")

                </td>
                @*<td>
                        @string.Format("{0:#,#}", @item.TienThuong).Replace(",", ",")

                    </td>
                    <td>

                        @string.Format("{0:#,#}", @item.TienPhat).Replace(",", ",")
                    </td>*@
                <td>
                    @String.Format("{0:dd/MM/yyyy}", @item.NgayNhanLuong)
                </td>
                <td>
                    @{
            var t = int.Parse(item.TongTienLuong);
                    }

                    @String.Format("{0:#,#}", t).Replace(",", ",")
                </td>

            </tr>
            }
        </tbody>
    </table>

</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/Index.cshtml
@{
    ViewBag.Title = "Lương nhân viên";
}

@using QuanLyNhanSu.Models
@model List<Luong>

<div class="container-fluid">
    <div class="">
        <div class="">
            <h1 class="page-header">
                Lương nhân viên
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
                </li>
                <li>
                    <i class="fa fa-money"></i> Lương
                </li>
            </ol>
        </div>
    </div>

    <div style="margin:10px">

        <a class="btn btn-primary" href="@Url.Action("DanhSachNhanLuong", "QuanLyLuong")">Danh sách nhận lương</a>
        <a class="btn btn-primary" href="@Url.Action("ThanhToanLuong", "QuanLyLuong")">Tính lương</a>
    </div>
    <div class="table-responsive">
        <table id="table-taikhoan" class="table  table-striped table-hover table-bordered ">
            <thead>
                <tr class="success">
                    <th>Mã nhân viên</th>
                    <th>Lương tối thiểu</th>
                    <th>Hệ số lương</th>
                    <th>Phụ cấp CV</th>
                    <th>Tiền bảo hiểm</th>
                    <th>Thuế (%)</th>
                    <th>Số bảng lương: @Model.Count</th>

                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.MaNhanVien</td>
                            <td>
                                @string.Format("{0:#,#}", @item.LuongToiThieu).Replace(",", ",")
                            </td>
                            <td>
                                @item.HeSoLuong
                            </td>
                            <td>
                                @item.PhuCap
                            </td>
                            <td>
                                <table class="table table-bordered">
                                    <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                                    <tr>
                                        <td>@item.BHXH</td>
                                        <td>@item.BHYT</td>
                                        <td>@item.BHTN</td>
                                    </tr>
                                </table>

                            </td>
                            <td>
                                @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")
                            </td>
                            <td>
                                <a class="btn btn-warning" href="@Url.Action("SuaBangLuong", "QuanLyLuong", new { @id = @item.MaNhanVien })"><i class="fa fa-pencil-square-o x5" aria-hidden="true"></i>Sửa</a>
                                <a class="btn btn-info" href="@Url.Action("ThanhToanMotNhanVien", "QuanLyLuong", new { @id = @item.MaNhanVien })">Tính lương</a>
                                <a class="btn btn-primary" href="@Url.Action("QuaTrinhTangLuong", "QuanLyLuong", new  {@id = @item.MaNhanVien })">Quá trình lương</a>

                            </td>
                        </tr>

                    }

                }

            </tbody>
        </table>
    </div>

</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/QuaTrinhTangLuong.cshtml
@model IEnumerable<QuanLyNhanSu.Models.CapNhatLuong>

@{
    ViewBag.Title = "Quá trình";
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Cập nhật bảng lương nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i><a href="@Url.Action("index","QuanLyLuong")">Lương</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Quá trình lương
            </li>
        </ol>
    </div>
</div>
<div class="table-responsive">
    <table id="table-taikhoan" class="table  table-striped table-hover table-bordered ">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Lương trước khi cập nhật
                </th>
                <th>
                    Lương sau khi cập nhật
                </th>
               
                <th>
                    @Html.DisplayNameFor(model => model.BHXH)
                </th>
                <th>
                    Hệ số lương
                </th>
                <th>
                    Thuế thu nhập
                </th>
                <th>
                    Ngày áp dụng
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Luong.MaNhanVien)
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.LuongHienTai).Replace(",", ",")
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.LuongSauCapNhat).Replace(",", ",")
                     
                    </td>
                    <td>
                        @*@string.Format("{0:#,#}", @item.BHXH).Replace(",", ",")*@
                        <table class="table table-bordered">
                            <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                            <tr>
                                <td>@item.BHXH</td>
                                <td>@item.BHYT</td>
                                <td>@item.BHTN</td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        @item.HeSoLuong
                        @*@string.Format("{0:#,#}", @item.PhuCap).Replace(",", ",")*@
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")
                    </td>
                    <td>
                        @String.Format("{0:dd/MM/yyyy}", @item.NgayCapNhat)
                    </td>
                 
                </tr>
            }
        </tbody>
    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/ThanhToanLuong.cshtml
@model QuanLyNhanSu.Models.ChiTietLuong


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ChiTietLuong</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaChiTietBangLuong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaChiTietBangLuong)
                @Html.ValidationMessageFor(model => model.MaChiTietBangLuong)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNhanVien, "MaNhanVien", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("MaNhanVien", String.Empty)*@
                @Html.ValidationMessageFor(model => model.MaNhanVien)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayNhanLuong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayNhanLuong)
                @Html.ValidationMessageFor(model => model.NgayNhanLuong)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TongTienLuong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTienLuong)
                @Html.ValidationMessageFor(model => model.TongTienLuong)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuongCoBan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuongCoBan)
                @Html.ValidationMessageFor(model => model.LuongCoBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BHXH, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BHXH)
                @Html.ValidationMessageFor(model => model.BHXH)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhuCap, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhuCap)
                @Html.ValidationMessageFor(model => model.PhuCap)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThueThuNhap, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThueThuNhap)
                @Html.ValidationMessageFor(model => model.ThueThuNhap)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TienThuong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TienThuong)
                @Html.ValidationMessageFor(model => model.TienThuong)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}