QuanLyNhanSu/Areas/admin/Controllers/QuanLyUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;
using System.Web.Security;
//using cExcel = Microsoft.Office.Interop.Excel;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class QuanLyUserController : AuthorController
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/QuanLyUser/
        public ActionResult Index()
        {
            var user = db.NhanViens.Where(x => x.MaNhanVien != "admin" && x.TrangThai == true).ToList();
            return View(user);
        }


        public ActionResult XoaUser(String id)
        {

            var a = db.NhanViens.Where(x => x.MaNhanVien == id).SingleOrDefault();
            var hd = db.HopDongs.Where(x => x.MaHopDong == id).SingleOrDefault();
            var luong = db.Luongs.Where(x => x.MaNhanVien == id).SingleOrDefault();
            var ctLuong = db.ChiTietLuongs.Where(x => x.MaNhanVien == id).ToList();
            foreach (var item in ctLuong)
            {
                db.ChiTietLuongs.Remove(item);
            }

            db.Luongs.Remove(luong);
            db.NhanViens.Remove(a);
            db.HopDongs.Remove(hd);

            db.SaveChanges();
            return Redirect("~/admin/QuanLyUser");
        }
        [HttpGet]
        public ActionResult UpdateUser(String id)
        {
            var user = db.NhanViens.Where(n => n.MaNhanVien == id).FirstOrDefault();
            UserValidate userVal = new UserValidate();

            userVal.MaNhanVien = user.MaNhanVien;
            userVal.HoTen = user.HoTen;
            userVal.MatKhau = user.MatKhau;
            userVal.GioiTinh = user.GioiTinh;

            userVal.MaChucVuNV = user.MaChucVuNV;
            userVal.QueQuan = user.QueQuan;
            userVal.HinhAnh = user.HinhAnh;
            userVal.DanToc = user.DanToc;
            userVal.sdt_NhanVien = user.sdt_NhanVien;
            userVal.MaHopDong = user.MaHopDong;

            userVal.NgaySinh = user.NgaySinh;
            userVal.TrangThai = user.TrangThai;
            userVal.MaChuyenNganh = user.MaChuyenNganh;
            userVal.MaTrinhDoHocVan = user.MaTrinhDoHocVan;
            userVal.MaPhongBan = user.MaPhongBan;

            userVal.CMND = user.CMND;
            userVal.XacNhanMatKhau = user.MatKhau;

            return View(userVal);
            //  return View(user);
        }
        [HttpPost]
        public ActionResult UpdateUser(UserValidate upUser)
        {
            upUser.XacNhanMatKhau = upUser.MatKhau;
            var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();

            if (ModelState.IsValid)
            {
                //var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();
                if (us != null)
                {

                    CapNhatTrinhDoHocVan capNhat = new CapNhatTrinhDoHocVan();
                    capNhat.MaNhanVien = upUser.MaNhanVien;
                    capNhat.NgayCapNhat = DateTime.Now.Date;
                    capNhat.MaTrinhDoTruoc = us.MaTrinhDoHocVan;
                    capNhat.MaTrinhDoCapNhat = upUser.MaTrinhDoHocVan;

                    us.MaNhanVien = upUser.MaNhanVien;
                    us.HoTen = upUser.HoTen;
                    us.MatKhau = upUser.MatKhau;
                    us.GioiTinh = upUser.GioiTinh;

                    us.MaChucVuNV = upUser.MaChucVuNV;
                    us.QueQuan = upUser.QueQuan;
                    us.HinhAnh = upUser.HinhAnh;
                    us.DanToc = upUser.DanToc;
                    us.sdt_NhanVien = upUser.sdt_NhanVien;
                    us.MaHopDong = upUser.MaHopDong;

                    us.NgaySinh = upUser.NgaySinh;
                    us.TrangThai = upUser.TrangThai;
                    us.MaChuyenNganh = upUser.MaChuyenNganh;
                    us.MaTrinhDoHocVan = upUser.MaTrinhDoHocVan;
                    us.MaPhongBan = upUser.MaPhongBan;
                    us.CMND = upUser.CMND;

                    var trinhdo = db.TrinhDoHocVans.Where(n => n.MaTrinhDoHocVan.Equals(us.MaTrinhDoHocVan)).FirstOrDefault();

                    var luong = db.Luongs.Where(n => n.MaNhanVien.Equals(us.MaNhanVien)).FirstOrDefault();

                    if (trinhdo.HeSoBac != null)
                    {
                        luong.HeSoLuong = luong.HeSoLuong < (double)trinhdo.HeSoBac ? (double)trinhdo.HeSoBac : luong.HeSoLuong;
                    }
                    else
                    { luong.HeSoLuong = 1; }



                    db.CapNhatTrinhDoHocVans.Add(capNhat);

                    db.SaveChanges();
                    return Redirect("/admin/QuanLyUser");

                }
            }
            return View(upUser);

        }//end update

        [HttpGet]

        public ActionResult ThemUser()
        {
            var chucvu = db.ChucVuNhanViens.ToList();
            var phongban = db.PhongBans.ToList();
            var hopdong = db.HopDongs.ToList();
            var chuyennganh = db.ChuyenNganhs.ToList();
            var trinhdo = db.TrinhDoHocVans.ToList();
            List<ChucVuNhanVien> list = chucvu;

            return View(new UserValidate());
        }


        [HttpPost]
        public ActionResult ThemUser(UserValidate nv)
        {
            nv.XacNhanMatKhau = nv.MatKhau;
            if (ModelState.IsValid)
            {
                ViewBag.err = String.Empty;
                var checkMaNhanVien = db.NhanViens.Any(x => x.MaNhanVien == nv.MaNhanVien);
                
                if (checkMaNhanVien)
                {
                    ViewBag.err = "tài khoản đã tồn tại";
                    //ModelState.AddModelError("MaNhanVien", "Mã tài khoản đã tồn tại");
                    return View(nv);
                }
                else
                {
                    Luong luong = new Luong();
                    HopDong hd = new HopDong();
                    NhanVien nvAdd = new NhanVien();
                    nvAdd.MaNhanVien = nv.MaNhanVien;
                    nvAdd.MatKhau = nv.MatKhau;
                    nvAdd.HoTen = nv.HoTen;
                    nvAdd.NgaySinh = nv.NgaySinh;
                    nvAdd.QueQuan = nv.QueQuan;
                    nvAdd.GioiTinh = nv.GioiTinh;
                    nvAdd.DanToc = nv.DanToc;
                    nvAdd.MaChucVuNV = nv.MaChucVuNV;
                    nvAdd.MaPhongBan = nv.MaPhongBan;
                    nvAdd.MaChuyenNganh = nv.MaChuyenNganh;
                    nvAdd.MaTrinhDoHocVan = nv.MaTrinhDoHocVan;
                    nvAdd.MaHopDong = nv.MaNhanVien;
                    nvAdd.TrangThai = true;
                    nvAdd.HinhAnh = "icon.jpg";

                    //add hop dong
                    hd.MaHopDong = nv.MaNhanVien;
                    hd.NgayBatDau = DateTime.Now.Date;

                    //tao bang luong
                    luong.MaNhanVien = nv.MaNhanVien;
                    luong.LuongToiThieu = 1150000;
                    luong.BHXH = 8;
                    luong.BHYT = 1.5;
                    luong.BHTN = 1;
                    var trinhdo = db.TrinhDoHocVans.Where(n=>n.MaTrinhDoHocVan.Equals(nv.MaTrinhDoHocVan)).FirstOrDefault();
                    var chucvu = db.ChucVuNhanViens.Where(n=>n.MaChucVuNV.Equals(nv.MaChucVuNV)).SingleOrDefault();
                    
                        if (trinhdo.MaTrinhDoHocVan.Equals(nv.MaTrinhDoHocVan))
                        {
                            luong.HeSoLuong = (double)trinhdo.HeSoBac;
                        }
                    
                    
                        if (chucvu.MaChucVuNV.Equals(nv.MaChucVuNV))
                        {
                            if (chucvu.HSPC != null)
                            {
                                luong.PhuCap = (double)chucvu.HSPC;
                            }
                            else
                            { luong.PhuCap = 0; }
                        }
                    


                    // tmp.Image = "~/Content/images/icon.jpg";
                    db.NhanViens.Add(nvAdd);
                    db.HopDongs.Add(hd);

                    db.Luongs.Add(luong);
                    // @ViewBag.add = "Đăng ký thành công";
                    db.SaveChanges();
                    //xác thực tài khoản trong ứng dụng
                    FormsAuthentication.SetAuthCookie(nvAdd.MaNhanVien, false);
                    //trả về trang quản lý

                    return Redirect("/admin/QuanLyUser");
                }
            }
            else
            {

                return View(nv);
            }
        }//end add nhan vien

        public ActionResult QuaTrinhCongTac(String id)
        {
            var ds = db.LuanChuyenNhanViens.Where(n => n.MaNhanVien == id).ToList();
            return View(ds);
        }

        public ActionResult XuatFileExel()
        {

            var ds = db.NhanViens.Where(n => n.MaNhanVien != "admin" && n.MaHopDong != null).ToList();
            var phong = db.PhongBans.ToList();
            var gv = new GridView();
            //===================================================
            DataTable dt = new DataTable();
            //Add Datacolumn
            DataColumn workCol = dt.Columns.Add("Họ tên", typeof(String));

            dt.Columns.Add("Phòng ban", typeof(String));
            dt.Columns.Add("Chức vụ", typeof(String));
            dt.Columns.Add("Học vấn", typeof(String));
            dt.Columns.Add("Chuyên ngành", typeof(String));

            //Add in the datarow


            foreach (var item in ds)
            {
                DataRow newRow = dt.NewRow();
                newRow["Họ tên"] = item.HoTen;
                newRow["Phòng ban"] = item.PhongBan.TenPhongBan;

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/Index.cshtml
@using QuanLyNhanSu.Models
@model List<NhanVien>

@{
    ViewBag.Title = "Nhân viên";
}
@{
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
    var td = db.TrinhDoHocVans.ToList();
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-user"></i> @*<a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>*@
                Nhân viên
            </li>
        </ol>
    </div>
</div>

<div>
    <div style="padding:10px">
        <a class="btn btn-primary" href="@Url.Action("ThemUser", "QuanLyUser")">
            Thêm nhân viên
        </a>

        <a class="btn btn-primary " href="@Url.Action("XuatFileExel", "QuanLyUser")">
            Xuất danh sách nhân viên
        </a>
    </div>
</div>




<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Họ tên
                </th>
                <th>
                    Trình độ văn hóa
                </th>
                <th>
                    Giới tính
                </th>
                <th>
                    Ngày bắt đầu
                </th>
                <th>
                    Số lượng: @Model.Count
                </th>

            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    string tenTrinhDo = string.Empty;
                    string gioitinh = string.Empty;
                    switch (item.GioiTinh)
                    {
                        case 0:
                            gioitinh = "Nữ";
                            break;
                        case 1:
                            gioitinh = "Nam";
                            break;
                        default:
                            gioitinh = "Khác";
                            break;
                    }


                    foreach (var t in td)
                    {
                        if (t.MaTrinhDoHocVan.Equals(item.MaTrinhDoHocVan))
                        {
                            tenTrinhDo = t.TenTrinhDo;
                            break;
                        }
                    }

                    <tr>
                        <td>@item.MaNhanVien</td>
                        <td>@item.HoTen</td>
                        <td>@tenTrinhDo</td>
                        <td>@gioitinh</td>
                        <td>
                            @String.Format("{0:dd/MM/yyyy}", @item.HopDong.NgayBatDau)
                        @{
                    DateTime ngaydau = Convert.ToDateTime(@item.HopDong.NgayBatDau);
                    DateTime ngaysau = DateTime.Now.Date;
                    TimeSpan Times = ngaysau - ngaydau;
                    
                    int sonam = (int)Times.Days/365;
                    
                        }
                       
                    </td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("QuaTrinhCongTac", "QuanLyUser", new { @id = @item.MaNhanVien })"><i class="fa fa-address-book"></i>Quá trình công tác</a>
                        <a class="btn btn-info" href="@Url.Action("QuaTrinhHoc", "QuanLyUser", new { @id = @item.MaNhanVien})">Học vấn</a>
                        <a class="btn btn-warning" href="@Url.Action("UpdateUser", "QuanLyUser", new {@id = @item.MaNhanVien })"><i class="fa fa-pencil-square-o x5" aria-hidden="true"></i>Sửa</a>
                        <a class="btn btn-danger" href="@Url.Action("XoaUser", "QuanLyUser", new { @id = @item.MaNhanVien })"><i class="fa fa-trash-o"></i>Xóa</a>
                    </td>
                </tr>
                }
            }

        </tbody>
    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/QuaTrinhCongTac.cshtml
@using QuanLyNhanSu.Models
@model List<LuanChuyenNhanVien>

@{
    ViewBag.Title = "Quá trình công tác";
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Quá trình công tác
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-fw fa-tasks"></i><a href="@Url.Action("index","QuanLyPhongBan")">Phòng ban</a>
            </li>
            <li>
                <i class="fa fa-bar-chart-o"></i> <a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
        </ol>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Phòng ban cũ
                </th>
                <th>
                    Phòng ban chuyển đến
                </th>
                <th>
                    Lý do
                </th>
                <th>
                    Ngày chuyển
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanVien.MaNhanVien)
                    </td>
                    @{
                QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
                String chuyendi = String.Empty;
                String chuyenden = String.Empty;
                foreach (var pb in db.PhongBans)
                {
                    if (pb.MaPhongBan.Equals(item.PhongBanChuyen))
                    {
                        chuyendi = pb.TenPhongBan;
                    }
                    if (pb.MaPhongBan.Equals(item.PhongBanDen))
                    {
                        chuyenden = pb.TenPhongBan;
                    }

                }
                    }
                    <td>
                        @chuyendi
                    </td>
                    <td>
                        @chuyenden
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LyDoChuyen)
                    </td>
                    <td>
                        @string.Format("{0:dd/MM/yyyy}", item.NgayChuyen)
                    </td>


                </tr>
            }
        </tbody>

    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/QuaTrinhHoc.cshtml
@*@model IEnumerable<QuanLyNhanSu.Models.CapNhatTrinhDoHocVan>*@
@using QuanLyNhanSu.Models
@model List<CapNhatTrinhDoHocVan>
@{
    ViewBag.Title = "Học vấn";
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
}


<div class="">
    <div class="">
        <h1 class="page-header">
            Quá trình học
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-fw fa-tasks"></i><a href="@Url.Action("index","QuanLyPhongBan")">Phòng ban</a>
            </li>
            <li>
                <i class="fa fa-bar-chart-o"></i> <a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
        </ol>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Họ tên
                </th>
                <th>
                    Chuyên ngành
                </th>
                <th>
                    Trình độ trước
                </th>
                <th>
                    Trình độ mới
                </th>
                <th>
                    Ngày cập nhật
                </th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanVien.HoTen)
                    </td>

                    @{
                String cn = String.Empty;
                foreach (var c in db.ChuyenNganhs)
                {
                    if (@item.NhanVien.MaChuyenNganh == c.MaChuyenNganh)
                    {
                        cn = c.TenChuyenNganh;
                    }
                }
                    }
                    <td>@cn</td>
                    @{
                String t = String.Empty;
                String s = String.Empty;

                foreach (var hv in db.TrinhDoHocVans)
                {

                    if (item.MaTrinhDoTruoc == hv.MaTrinhDoHocVan)
                    {
                        t = hv.TenTrinhDo;
                    }
                    if (item.MaTrinhDoCapNhat == hv.MaTrinhDoHocVan)
                    {
                        s = hv.TenTrinhDo;
                    }
                }
                    }
                    <td>
                        @t
                    </td>
                    <td>
                        @s
                    </td>

                    <td>
                        @String.Format("{0:dd/MM/yyyy}", @item.NgayCapNhat)
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/ThemUser.cshtml
@{
    ViewBag.Title = "Thêm nhân viên";
}

@*@model QuanLyNhanSu.Models.NhanVien*@
@using QuanLyNhanSu.Models
@*@model NhanVien*@
@model UserValidate

<div class="">
    <div class="">
        <h1 class="page-header">
            Thêm nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-user"></i> <a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
            <li>
                <i class="fa fa-user"></i>Thêm nhân viên
            </li>
        </ol>
    </div>
</div>
<form class="form-horizontal" method="post" role="form">
    @*@Url.Action("ThemUser", "QuanLyUser")*@
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    @*@Html.HiddenFor(model => model.MaNhanVien)*@

    @* ma nhan vien *@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Mã nhân viên</label>
        </div>

        <div class="col-md-4 col-sm-8">
            <input type="text" name="MaNhanVien"
                   class="form-control"
                   id="MaNhanVien"
                   value="@Model.MaNhanVien"
                   required />

        </div>
        <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5" style="height:15px">
            <label class="control-label text-danger">
                @ViewBag.err
                @Html.ValidationMessageFor(n => n.MaNhanVien)
            </label>
        </div>
    </div>
    @* mat khau *@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Mật khẩu</label>
        </div>

        <div class="col-md-4 col-sm-8">
            <input type="password" name="MatKhau"
                   class="form-control"
                   id="MatKhau"
                   value="@Model.MatKhau"
                   required />
        </div>
        <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5" style="height:15px">
            <label class="control-label text-danger">
                @Html.ValidationMessageFor(n => n.MatKhau)
            </label>
        </div>
    </div>

    @*xac mat khau *@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Xác nhận mật khẩu</label>
        </div>

        <div class="col-md-4 col-sm-8">
            <input type="password" name="XacNhanMatKhau"
                   class="form-control"
                   id="MatKhau"
                   value="@Model.XacNhanMatKhau"
                   required />
        </div>
        <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5" style="height:15px">
            <label class="control-label text-danger">
                @Html.ValidationMessageFor(n => n.XacNhanMatKhau)
            </label>
        </div>
    </div>

    @* ho ten *@
    <div class="form-group">
        <!---start-->
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Họ tên</label>
        </div>

        <div class="col-md-4 col-sm-8">
            <input type="text" name="HoTen"
                   class="form-control"
                   id="HoTen"
                   value="@Model.HoTen"
                   required />
        </div>
        
        <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5" style="height:15px">
            <label class="control-label text-danger">
                @Html.ValidationMessageFor(n => n.HoTen)
            </label>
        </div>
            <!---end--->
        </div>
 
    @* gioi tinh*@
    <div class="form-group">
        <!---start-->
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Giới tính</label>
        </div>

        <div class="col-md-4 col-sm-8">
            <div class="radio-inline">
                <label><input type="radio" name="GioiTinh" value="1" checked>Nam</label>
            </div>
            <div class="radio-inline">
                <label><input type="radio" name="GioiTinh" value="0">Nữ</label>
            </div>
            <div class="radio-inline">
                <label><input type="radio" name="GioiTinh" value="2">Khác</label>
            </div>
        </div>

        <!---end--->

    </div>
   
    @* chuc vu*@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Chức vụ</label>
        </div>
        <div class="col-md-4 col-sm-8">
            @{QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
            var chucvu = db.ChucVuNhanViens.ToList();
            }
            <select name="MaChucVuNV" class="form-control">
                @foreach (var item in chucvu)
                {
                <option value="@item.MaChucVuNV.ToString()" selected>@item.TenChucVu</option>
                }
            </select>

            @Html.ValidationMessageFor(model => model.MaChucVuNV)
        </div>
    </div>
    @* phong ban*@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Phòng ban</label>
        </div>
        <div class="col-md-4 col-sm-8">
            @{
                var phongban = db.PhongBans.ToList();
            }
            <select name="MaPhongBan" class="form-control">
                @foreach (var item in phongban)
                {
                <option value="@item.MaPhongBan.ToString()" selected>@item.TenPhongBan</option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.MaPhongBan)
        </div>
    </div>
    @* chuyen nganh*@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Chuyên ngành</label>
        </div>
        <div class="col-md-4 col-sm-8">
            @{
                var chuyenNganh = db.ChuyenNganhs.ToList();
            }
            <select name="MaChuyenNganh" class="form-control">
                @foreach (var item in chuyenNganh)
                {
                <option value="@item.MaChuyenNganh.ToString()" selected>@item.TenChuyenNganh</option>
                }
            </select>

        </div>
    </div>
    @* trinh do hoc van *@
    <div class="form-group">
        <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
            <label>Trình độ học vấn</label>
        </div>
        <div class="col-md-4 col-sm-8">
            @{
                var hocVan = db.TrinhDoHocVans.ToList();
            }
            <select name="MaTrinhDoHocVan" class="form-control">
                @foreach (var item in hocVan)
                {
                <option value="@item.MaTrinhDoHocVan.ToString()" selected>@item.TenTrinhDo</option>
                }
            </select>
        </div>
    </div>
    @* button submit*@
    <div class="form-group">
        <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5">
            <input type="submit" value="Thêm nhân viên" class="btn btn-primary" />
        </div>
    </div>

</form>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/XoaUser.cshtml
@{
    ViewBag.Title = "XoaUser";
}

<h2>XoaUser</h2>