QuanLyNhanSu/Models/KhenThuong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuong
    {
        public string MaNhanVien { get; set; }
        public System.DateTime ThangThuong { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> TienThuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}

QuanLyNhanSu/Areas/admin/Controllers/KhenThuongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class KhenThuongController : Controller
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/KhenThuong/
        public ActionResult Index()
        {
            var t = db.KhenThuongs.ToList();
            return View(t);
        }
        [HttpGet]
        public ActionResult khen()
        {
            var nv = db.NhanViens.ToList();
        
            return View(new KhenThuong());
        }
        [HttpPost]
        public ActionResult khen(KhenThuong kt)
        {
            //var ct = db.ChiTietLuongs.Where(n => n.MaNhanVien == kt.MaNhanVien).FirstOrDefault();
                     
            KhenThuong ad = new KhenThuong();
            ad.MaNhanVien = kt.MaNhanVien;
            ad.ThangThuong = kt.ThangThuong;
            ad.TienThuong = kt.TienThuong;
            ad.LyDo = kt.LyDo;

            db.KhenThuongs.Add(ad);
            db.SaveChanges();
            return Redirect("/admin/KhenThuong"); 
        }
	}
}

QuanLyNhanSu/Areas/admin/Views/KhenThuong/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.KhenThuong>

@{
    ViewBag.Title = "Danh sách khen thưởng";
}


<div class="">
    <div class="">
        <h1 class="page-header">
            Khen thưởng nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Khen thưởng
            </li>
        </ol>
    </div>
</div>


<div style="margin:10px">

    <a class="btn btn-primary" href="@Url.Action("khen", "KhenThuong")">Khen Thưởng</a>
</div>

<table id="table-taikhoan" class="table table-responsive table-bordered table-striped">
    <thead>
        <tr class="success">
            <th>
                Mã nhân viên
            </th>
            <th>
                Tháng thưởng
            </th>
            <th>
                Lý do
            </th>
            <th>
                Tiền thưởng
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NhanVien.MaNhanVien)
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", @item.ThangThuong)
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LyDo)
                </td>
                <td>
                    @string.Format("{0:#,#}", @item.TienThuong).Replace(",", ",")
                    
                </td>

            </tr>
        }
    </tbody>
</table>

QuanLyNhanSu/Areas/admin/Views/KhenThuong/khen.cshtml
@*@model QuanLyNhanSu.Models.KhenThuong*@

@using QuanLyNhanSu.Models
@model KhenThuong

@{
    ViewBag.Title = "Khen thưởng";
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
    var nhanvien = db.NhanViens.Where(n => n.MaNhanVien != "admin").ToList();
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Khen thưởng nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Khen thưởng
            </li>
        </ol>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-offset-2 col-md-8">
        <div class="form-horizontal">

            @Html.ValidationSummary(true)

            <div class="form-group">
                <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
                    <label>Nhân viên</label>
                </div>
                <div class="col-md-4 col-sm-8">
                    @*@Html.DropDownList("@ViewBag.nhanvien", "ma nhan vien")*@

                    <input list="browsers" name="MaNhanvien" class="form-control">
                    <datalist id="browsers">
                        @foreach (var item in nhanvien)
                        {
                            <option value="@item.MaNhanVien.ToString()">@item.MaNhanVien - @item.HoTen</option>
                        }
                      
                    </datalist>

                    @*<select name="MaNhanvien" class="form-control">
                        @foreach (var item in nhanvien)
                        {
                            <option value="@item.MaNhanVien.ToString()">@item.MaNhanVien - @item.HoTen</option>
                        }
                    </select>*@
                    @Html.ValidationMessageFor(model => model.MaNhanVien)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Tháng thưởng</label>
                <div class="col-md-4 col-sm-8">
                    <input type="date" name="ThangThuong" required class="form-control" />

                    @Html.ValidationMessageFor(model => model.ThangThuong)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Tiền thưởng(nếu có)</label>

                <div class="col-md-4 col-sm-8">
                    <input name="TienThuong" class="form-control" title="Tiền thưởng" />
                    @Html.ValidationMessageFor(model => model.TienThuong)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Lý do</label>

                <div class="col-md-4 col-sm-8">
                    @Html.TextAreaFor(model => model.LyDo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LyDo)
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-md-offset-5 col-sm-8">
                    <input type="submit" value="Xác nhận" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

<div class="clearfix"></div>